#include "fonts.h"

extern "C" {
    // Bring in the flash-resident read-only blocks generated by the script
    extern const lv_font_t font_atkinson_10_raw;
    extern const lv_font_t font_atkinson_14_raw;
    extern const lv_font_t font_atkinson_18_raw;
    extern const lv_font_t font_jetbrains_10_raw;
    extern const lv_font_t font_jetbrains_14_raw;
    extern const lv_font_t font_jetbrains_24_raw;

    // Define the actual public RAM allocations
    lv_font_t font_atkinson_10;
    lv_font_t font_atkinson_14;
    lv_font_t font_atkinson_18;
    lv_font_t font_jetbrains_10;
    lv_font_t font_jetbrains_14;
    lv_font_t font_jetbrains_24;

    void fonts_init(void) {
        // Step 1: Clone the font structures from Flash into RAM variables
        font_atkinson_10 = font_atkinson_10_raw;
        font_atkinson_14 = font_atkinson_14_raw;
        font_atkinson_18 = font_atkinson_18_raw;
        font_jetbrains_10 = font_jetbrains_10_raw;
        font_jetbrains_14 = font_jetbrains_14_raw;
        font_jetbrains_24 = font_jetbrains_24_raw;

        // Step 2: Hotwire fallback pointers to catch missing utility icons and keyboard glyphs
        font_atkinson_10.fallback = &lv_font_montserrat_10;
        font_atkinson_14.fallback = &lv_font_montserrat_14;
        font_atkinson_18.fallback = &lv_font_montserrat_14;
        font_jetbrains_10.fallback = &lv_font_montserrat_10;
        font_jetbrains_14.fallback = &lv_font_montserrat_14;
        font_jetbrains_24.fallback = &lv_font_montserrat_14;
    }
}
